// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteFeedFollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFollowByUserAndFeed = `-- name: DeleteFollowByUserAndFeed :exec

DELETE FROM feed_follows
WHERE feed_follows.user_id = $1
AND feed_follows.feed_id = $2
`

type DeleteFollowByUserAndFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFollowByUserAndFeed(ctx context.Context, arg DeleteFollowByUserAndFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowByUserAndFeed, arg.UserID, arg.FeedID)
	return err
}
