// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markFeedFetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markFetchedAt = `-- name: MarkFetchedAt :exec

UPDATE feeds
SET 
last_fetched_at = $1, 
updated_at = $2

WHERE ID = $3
`

type MarkFetchedAtParams struct {
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) MarkFetchedAt(ctx context.Context, arg MarkFetchedAtParams) error {
	_, err := q.db.ExecContext(ctx, markFetchedAt, arg.LastFetchedAt, arg.UpdatedAt, arg.ID)
	return err
}
